<p>Please be carefully using this functions.</p>
<fieldset>
    <legend>Grow Stage</legend>
    <button name="stage" value="1" class="btn btn-success" type="submit">
        Grow
    </button>
    <button name="stage" value="2" class="btn btn-warning" type="submit">
        Flowering
    </button>
    <button name="stage" value="3" class="btn btn-danger" type="submit">
        Disease
    </button>
</fieldset>

<fieldset>
    <legend>Lights</legend>
    Red:
    <button disabled type="button" class="btn btn-primary">On</button>
    <button disabled type="button" class="btn btn-primary">Off</button>
    Blue:
    <button disabled type="button" class="btn btn-danger">On</button>
    <button disabled type="button" class="btn btn-danger">Off</button>
    UV:
    <button disabled type="button" class="btn btn-default">On</button>
    <button disabled type="button" class="btn btn-default">Off</button>
    IR:
    <button disabled type="button" class="btn btn-default">On</button>
    <button disabled type="button" class="btn btn-default">Off</button>
</fieldset>
<fieldset>
    <legend>Equipment</legend>
    Heater:
    <button disabled type="button" class="btn btn-default">On</button>
    <button disabled type="button" class="btn btn-default">Off</button>
    Humiditifier:
    <button disabled type="button" class="btn btn-default">On</button>
    <button disabled type="button" class="btn btn-default">Off</button>
    Fan:
    <button disabled type="button" class="btn btn-default">On</button>
    <button disabled type="button" class="btn btn-default">Off</button>
</fieldset>