<div class="row">
    <div class="col-md-4">
        <h2>Lighting</h2>
        <div class="col-md-4">
            <fieldset>
                <h3>Growing</h3>
                <label>Red</label><input name="growing_red" type="text" class="form-control" placeholder="Red" value="<?php echo $actualPreset['growing_red']?>">
                <label>Blue</label><input name="growing_blue" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['growing_blue']?>">
                <label>UV</label><input name="growing_uv" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['growing_uv']?>">
                <label>IR</label><input name="growing_ir" type="text" class="form-control" placeholder="IR" value="<?php echo $actualPreset['growing_ir']?>">
            </fieldset>
        </div>
        <div class="col-md-4">
            <fieldset>
                <h3>Flowering</h3>
                <label>Red</label><input name="flowering_red" type="text" class="form-control" placeholder="Red" value="<?php echo $actualPreset['flowering_red']?>">
                <label>Blue</label><input name="flowering_blue" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['flowering_blue']?>">
                <label>UV</label><input name="flowering_uv" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['flowering_uv']?>">
                <label>IR</label><input name="flowering_ir" type="text" class="form-control" placeholder="IR" value="<?php echo $actualPreset['flowering_ir']?>">
            </fieldset>
        </div>
        <div class="col-md-4">
            <fieldset>
                <h3>Sick</h3>
                <label>Red</label><input name="sick_red" type="text" class="form-control" placeholder="Red" value="<?php echo $actualPreset['sick_red']?>">
                <label>Blue</label><input name="sick_blue" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['sick_blue']?>">
                <label>UV</label><input name="sick_uv" type="text" class="form-control" placeholder="Blue" value="<?php echo $actualPreset['sick_uv']?>">
                <label>IR</label><input name="sick_ir" type="text" class="form-control" placeholder="IR" value="<?php echo $actualPreset['sick_ir']?>">
            </fieldset>
        </div>
    </div>
</div>